#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'appendAndDelete' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING s
#  2. STRING t
#  3. INTEGER k
#

def appendAndDelete(s, t, k):
    # Write your code here
    i = 0
    while i<len(s) and i<len(t) and s[i]==t[i]:
        i+=1
    
    s1 = len(s[i:])
    t1 = len(t[i:])
    if s1+t1>k:
        print("No")
        return "No"
    elif s1+t1==k:
        print("Yes")
        return "Yes"
    elif (len(s)+len(t))-k<=0:
        print("Yes")
        return "Yes"
    elif abs((len(s)+len(t))-k)%2==0:
         print("Yes")
         return "Yes"
    else:
        print("No")
        return "No"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    t = input()

    k = int(input().strip())

    result = appendAndDelete(s, t, k)

    fptr.write(result + '\n')

    fptr.close()
