#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'bonAppetit' function below.
#
# The function accepts following parameters:
#  1. INTEGER_ARRAY bill
#  2. INTEGER k
#  3. INTEGER b
#

def bonAppetit(bill, k, b):
    # Write your code here
    # print bon appetit if the bill spilt fairly or print money Brian owes Anna
    sumbill=0
    brianbill=0
    for i in range(len(bill)):
        sumbill+=bill[i]
    brianbill= int((sumbill-bill[k])/2)
    
    if brianbill==b:
        print("Bon Appetit")
    elif brianbill<=b:
        print(b-brianbill)

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    bill = list(map(int, input().rstrip().split()))

    b = int(input().strip())

    bonAppetit(bill, k, b)
