#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'compareTriplets' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def compareTriplets(a, b):
    # Write your code here
    alice=0
    bob=0
    for i in range (0,len(a)):
        if a[i]>b[i]:
          #if Alice's digit is larger than Bob's digit, ALice receives 1 point
            alice+=1
        elif a[i]<b[i]:
           #else if Alice's digit is smaller than Bob's digit, Bob receives 1 point
            bob+=1
        else:
          #else if Alice's digit is equal to Bob's digit, nobody receives a point
            continue        
    li =[alice,bob]
    return li
     

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
