#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    # Write your code here
    lastcolnum=len(arr)-1 # array starts with row[0], so len(arr)-1 is 3-1 =2 
    left_arr=[]
    right_arr=[]

    for i in range(len(arr)):
    #get the left diagonal digit,i.e. [0][0],[1][1],[2][2]
        left_arr.append(arr[i][i])
        #print (left_arr)
    
    for j in range(len(arr)):
    #get the right diagonal digit,i.e. [0][2],[1][1],[2][0]
        right_arr.append(arr[j][lastcolnum])
        lastcolnum-=1
        #print (right_arr)
        
    return abs(sum(left_arr)-sum(right_arr))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
