#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'kangaroo' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. INTEGER x1
#  2. INTEGER v1
#  3. INTEGER x2
#  4. INTEGER v2
#

def kangaroo(x1, v1, x2, v2):
    # Write your code here
    #return yes or No

   k1K2Position=x1-x2
   K1k2JumpsDist=v2-v1
   #2nd kangaroo starting position is larger than 1st Kangaroo
   #2nd kangaroo jumping distance is larger than 1st Kangaroo
   if x2>x1 and v2>v1:
        IsK1K2InSameDistPossible="NO"
   else:
    #2nd kangaroo and 1st kangaroo jumping distance are the same
    if v2-v1 == 0:
        IsK1K2InSameDistPossible="NO"
    else:
        #2nd kangaroo and 1st kangaroo number of jumps are the same
        if k1K2Position % K1k2JumpsDist==0:
           IsK1K2InSameDistPossible="YES"
        else:
           IsK1K2InSameDistPossible="NO"
      
   return IsK1K2InSameDistPossible
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    x1 = int(first_multiple_input[0])

    v1 = int(first_multiple_input[1])

    x2 = int(first_multiple_input[2])

    v2 = int(first_multiple_input[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + '\n')

    fptr.close()
